### ISSUE TITLE
Add support for -I

### ISSUE THREAD

**Issue by vrurg** [Leont/app-prove6#1]
Would it be possible to provide support for `-I` option to add own custom lib directories? It was in the old version of `prove6`.

**Comment by Leont** [comment]
It's still supported, though the it changed from `-I=$dir` to `-I$dir` (or `--incdir=$dir`, or `--incdir $dir`), to be more conformant with normal unix command line tools.

**Comment by vrurg** [comment]
I didn't see neither in the help output. Ok, thanks!

**Comment by Leont** [comment]
That's an oversight, I'll add it to the docs
