### ISSUE TITLE
prove6 looks for files ending with '.t'

### ISSUE THREAD

**Issue by frithnanth** [Leont/app-prove6#4]
It seems that the recommended extension for Raku test files is now `.rakutest`.

**Comment by Leont** [comment]
I'm not sure what you're trying to tell me here.

If you want it to look for `.rakutest`, then I can tell you it already does so (and has been doing so since 0.0.11).

If you want it to no longer look for `.t`, then I'd have to disagree. There's way too much code out there to drop it now.

**Comment by frithnanth** [comment]
I agree with you on preserving compatibility with the `.t` extension.
On the other hand on my system prove6 output this when all the files in the t/ directory end with `.rakutest`:
>$ prove6
All tests successful.
Files=0, Tests=0,  0 wallclock secs
Result: NOTESTS

zef says that TAP is already installed and there's no App::prove6. Any hint?

**Comment by frithnanth** [comment]
It seems to be an issue with zef not showing there's a new version of TAP.
I cloned this repository and run `zef install .` from inside it. Only then zef downloaded the new version of TAP.
Sorry!
